global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'airflow-statsd'
    static_configs:
      - targets: ['statsd-exporter:9102']
  # - job_name: 'otel-collector'
  #   scrape_interval: 1m
  #   static_configs:
  #     - targets: ['otel-collector:8889']